[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@snyk/netlify-plugin-security"

  [plugins.inputs]
    failOnIssues = "high"
    monitor = true
    severityThreshold = "high"
